:sectnums:

= リバースエンジニアリングと法律

[.text-right]
sei0o

「リバースエンジニアリング」は誰かが開発したモノを分解・解析することですfootnote:[対義語として「フォワードエンジニアリング」が存在し、アプリやサービスを開発することを指します。もっとも、この語自体はリバースエンジニアリングの文脈でしか見かけることがないのですが…]。ソフトウェアであれば、リバースエンジニアリングによって先行する製品の仕組みを理解したり、内部で使用しているライブラリを見つけたりするなど、ただ使用するだけでは得られない様々な情報を知ることが可能になります。しかしながら、ゲームに対するチート・リーク行為の手段としても悪用されやすいのも事実です。この記事では、リバースエンジニアリングと深い関わりを持つ法律の関係について調査しました。

なお、リバースエンジニアリングという語そのものはソフトウェアに限らず自動車や軍事の分野でも使われていますが、本文では対象をソフトウェアに限定します。残念なことに筆者は法曹ではなくただの心配性な素人なので、以下の記述は公的機関・研究機関が公開しているPDFファイルや判例と首っ引きになってまとめたものになります。適宜文中に示した引用元をご覧になることをおすすめします。

== リバースエンジニアリングの分類

[quote]
____
[%hardbreaks]
（著作物に表現された思想又は感情の享受を目的としない利用）
第三十条の四　著作物は、次に掲げる場合その他の当該著作物に表現された思想又は感情を自ら享受し又は他人に享受させることを目的としない場合には、その必要と認められる限度において、いずれの方法によるかを問わず、利用することができる。ただし、当該著作物の種類及び用途並びに当該利用の態様に照らし著作権者の利益を不当に害することとなる場合は、この限りでない。

[%hardbreaks]
一　著作物の録音、録画その他の利用に係る技術の開発又は実用化のための試験の用に供する場合
二　情報解析（多数の著作物その他の大量の情報から、当該情報を構成する言語、音、影像その他の要素に係る情報を抽出し、比較、分類その他の解析を行うことをいう。第四十七条の五第一項第二号において同じ。）の用に供する場合
三　前二号に掲げる場合のほか、著作物の表現についての人の知覚による認識を伴うことなく当該著作物を電子計算機による情報処理の過程における利用その他の利用（プログラムの著作物にあつては、当該著作物の電子計算機における実行を除く。）に供する場合
____

* リバースエンジニアリングと一口にいっても、その対象・目的・程度によって見解はさまざまに分かれています
* 対象による分類
** プラットフォーム
--- OSなどが該当します
--- 脆弱性などが見つかれば被害が拡大する、相互運用性がない場合範囲広くに影響する
-- 一般的なアプリケーション
- 目的による分類
-- 競合するソフトウェアの作成
--- インターフェースの解析によって相互運用性を高める→ユーザーのロックインを防ぐ効果
--- パクり
-- セキュリティ目的
--- 第1群
--- セキュリティ目的、というのがそもそも何であるのか
---- 学習、研究、脆弱性調査
-- チート行為
-- その他(趣味など)
--- 一番気になるのが
-- 公共的な用途
--- 従来から認められている
- 程度による分類
-- 「第1群」
-- 「第2群」

=== 対象による分類

*プラットフォーム* 

=== 目的による分類

*チート行為* リバースエンジニアリングの手法等には関係なく、ゲームを有利に進めるためのチート行為は違法であり、刑事事件として、私電磁的記録不正作出・同供用罪や電子計算機損壊等業務妨害罪が成立することがあります。また、著作権法の権利制限規定(第三十条の四ただし書きfootnote:[条文と中心となる内容を定めたあとに続く、「ただし」で始まる文のこと。例外を示す場合によく使われる。]など)においても権利制限の対象外となります。一方で、ゲームの記録を直接書き換えることなく、サービス側が公開していない新キャラなどの情報を解析によって得るリーク行為についての判例は見当たりませんでした。

=== 程度による分類


この分類は2018年の著作権法改正によって大きく変化しました。

== グレーゾーン

- リバースエンジニアリングでは

- 海外でのリーク行為
-- 韓国版ミリシタでのリーク
--- 韓国では日本よりもリバースエンジニアリングに対して明確に寛容な立場を取っている <<1>>

- 法律


- 利用規約
-- 該当する行為が合法であっても、サービス側から同意を求められる利用規約において、多くの場合リバースエンジニアリングが禁止されています。そして、有効な契約条項への違反(債務不履行)に対しては損害賠償の請求が認められています。
-- 利用規約は契約なのか
-- 「同意」を押せば契約が成立するのか
-- 利用規約に同意する前にリバースエンジニアリングを行えば禁止事項には引っかからないのではないか

- 事件
-- どの法律を利用して裁かれるかは事件によって異なります

-- 対して、チートでないリバースエンジニアリングについては
--- 著作権法
---- 強行規定と任意規定
--- 独占禁止法
--- 消費者契約法
--- 民法
---- シュリンクラップ契約
---- 契約がそもそも成立しているか
- この記事について

- 「法令適用事前確認手続(ノーアクションレター制度)」は民間企業など国民が、法に触れる心配のある行いをしようとするときに、法令を所管する省庁に直接問い合わせる制度です。
-- 1ヶ月程度で回答が返ってくるようです。問い合わせ先によっては氏名や住所の公表について同意を求める欄もありますが、同意しなければ公表されず、回答のみが公表されるようですfootnote:[「文部科学省における法令適用事前確認手続に係る照会書」 http://www.mext.go.jp/component/b_menu/other/__icsFiles/afieldfile/2012/09/21/1326070_1.pdf]。
-- それぞれの省庁のWebサイトにおいて、対象となる所管法令についての窓口が示されている
-- 著作権法を所管するfootnote:[「所管の法令等
」 http://www.bunka.go.jp/seisaku/bunka_gyosei/shokan_horei/index.html]文化庁ではそもそも手続に関するページがない
-- 親玉となる文部科学省では問い合わせ先が一覧になっており、「著作権課」も含まれているものの、著作権法についての問い合わせは受け付けていないfootnote:[「文部科学省における法令適用事前確認手続について」 http://www.mext.go.jp/b_menu/toukei/005/020401.htm]。
-- 消費者庁は手続きを受け付け、消費者契約法が所管であるfootnote:[「所管の法令等
」 https://www.caa.go.jp/law/laws/]が、やはりリバースエンジニアリング禁止条項に関係するであろう第10条の問い合わせ先は掲載されていないfootnote:[「各法律の条項との問い合わせ先一覧」 https://www.caa.go.jp/law/nal/pdf/b_ichiran_180330_0001.pdf]。
-- 類似の制度である「グレーゾーン解消制度」は、事業を始めようとする人が対象であり、事業内容の提出などを求められる。


- 2019年1月1日に改正著作権法が施行されました。
- 独占禁止法
- 実は結構前から議論されている
-- 改正前の条文に対しても、

http://www.bunka.go.jp/seisaku/chosakuken/hokaisei/h30_hokaisei/
- 改正著作権法
		http://www.cric.or.jp/db/domestic/a1_index.html
>（著作物に表現された思想又は感情の享受を目的としない利用）
> 第三十条の四　著作物は、次に掲げる場合その他の当該著作物に表現された思想又は感情を自ら享受し又は他人に享受させることを目的としない場合には、その必要と認められる限度において、いずれの方法によるかを問わず、利用することができる。ただし、当該著作物の種類及び用途並びに当該利用の態様に照らし著作権者の利益を不当に害することとなる場合は、この限りでない。
> 
> 一　著作物の録音、録画その他の利用に係る技術の開発又は実用化のための試験の用に供する場合
> 二　情報解析（多数の著作物その他の大量の情報から、当該情報を構成する言語、音、影像その他の要素に係る情報を抽出し、比較、分類その他の解析を行うことをいう。第四十七条の五第一項第二号において同じ。）の用に供する場合
> 三　前二号に掲げる場合のほか、著作物の表現についての人の知覚による認識を伴うことなく当該著作物を電子計算機による情報処理の過程における利用その他の利用（プログラムの著作物にあつては、当該著作物の電子計算機における実行を除く。）に供する場合
		[●100●知財研紀要  2006 17  コンピュータ・プログラムの保護に関する 米・EU・日・韓の比較法的研究 －プログラム  リバース・エンジニアリングを中心に－ http://www.iip.or.jp/pdf/fellow/detail05j/17_17.pdf]
			EUディレクティブ→許可
			US→フェアユース
			韓国→許可に近い
		http://www.j.u-tokyo.ac.jp/jjweb/research/MAR2002/sakuma_hisashi.pdf
		http://www.it-houmu.com/archives/1514
			利用規約違反の場合でも違約金などは消費者契約法によって制限される
	https://www.kantei.go.jp/jp/singi/titeki2/tyousakai/kensho_hyoka_kikaku/2018/sangyou/dai5/siryou2-4.pdf
		３ページ目の「第1層」「第２層」


https://www.ipa.go.jp/files/000072543.pdf 12ページ
> そして、この権利者の利益を通常害さないと評価できる行為類型の代表例として、「セキュリティ確保のためのソフトウエアの調査解析等」があげられている。これにより、脆弱性調査のためのリバース・エンジニアリング行為が著作権法上禁止されているのではないかという問題については、決着をみたものと考えられる。もっとも、ライセンス契約におけるリバース・エンジニアリング禁止の効力が、脆弱性情報調査に対しても有効なのか、という問題は、依然として存在している。

http://www.mext.go.jp/b_menu/shingi/bunka/gijiroku/013/06073103/002.htm
http://www.j.u-tokyo.ac.jp/jjweb/research/MAR2002/sakuma_hisashi.pdf 17ページ

- 著作権者の利益を不当に害するとはすなわちリバースエンジニアリングによって取得した情報でチートを行ったり、情報のリークを行ったりすることと考えられる。
-- SNSでたまに見かけますよね
- ただし、利用規約でリバースエンジニアリングが禁止されている場合、法律と利用規約のどちらが優先されるかはわからない
- 特段の定めがない場合、契約は法律に優先する(契約自由の原則)
-- 法律は「任意規定」の場合
-- オーバーライド可能
- 法律が「強行規定」の場合、法律が契約に優先する
-- 公の秩序に関する規定は「強行規定」とされ、これに矛盾する契約の項目は無効になる
- 著作権法第三十条の四などがどちらに属するものかは確定していない
-- 特許法では、試験と研究には特許権の効力が及ばないことになっている
-- 競争法の立場から、リバースエンジニアリングによって競争が加速する(公の秩序に貢献する)という見方
-- リバースエンジニアリング
-- 判例の積み重ねを待つしかない
- ミリシタの利用規約でもリバースエンジニアリングは禁止されている
- よってこの記事も利用規約から見ればグレー(民法上のリスクがある)
- しかしながら、リバースエンジニアリングをハードウェアやソフトウェアに対して行った資料が商用・非商用にかかわらずちらほら見かけるので、どうなるのか気になっている
-- みんなで渡れば怖くない、と正当化する意図はない
- ほとんどテンプレのような形でリバースエンジニアリングを禁止する条項が設定されているので、結局改正の意味がないのでは
