:sectnums:

= リバースエンジニアリングと法律

[.text-right]
sei0o

「リバースエンジニアリング」は誰かが開発したモノを分解・解析することですfootnote:[対義語として「フォワードエンジニアリング」が存在し、アプリやサービスを開発することを指します。もっとも、この語自体はリバースエンジニアリングの文脈でしか見かけることがないのですが…]。ソフトウェアであれば、リバースエンジニアリングによって先行する製品の仕組みを理解したり、内部で使用しているライブラリを見つけたりするなど、ただ使用するだけでは得られない様々な情報を知ることが可能になります。しかしながら、ゲームに対するチート・リーク行為の手段としても悪用されやすいのも事実です。この記事では、リバースエンジニアリングと深い関わりを持つ法律の関係について調査しました。

なお、リバースエンジニアリングという語そのものはソフトウェアに限らず自動車や軍事の分野でも使われていますが、本文では対象をソフトウェアに限定します。残念なことに筆者は法曹ではなくただの心配性な素人なので、以下の記述は公的機関・研究機関が公開しているPDFファイルや判例と首っ引きになってまとめたものになります。適宜文中に示した引用元をご覧になることをおすすめします。

== リバースエンジニアリングの分類

[quote]
____
[%hardbreaks]
（著作物に表現された思想又は感情の享受を目的としない利用）
第三十条の四　著作物は、次に掲げる場合その他の当該著作物に表現された思想又は感情を自ら享受し又は他人に享受させることを目的としない場合には、その必要と認められる限度において、いずれの方法によるかを問わず、利用することができる。ただし、当該著作物の種類及び用途並びに当該利用の態様に照らし著作権者の利益を不当に害することとなる場合は、この限りでない。

[%hardbreaks]
一　著作物の録音、録画その他の利用に係る技術の開発又は実用化のための試験の用に供する場合
二　情報解析（多数の著作物その他の大量の情報から、当該情報を構成する言語、音、影像その他の要素に係る情報を抽出し、比較、分類その他の解析を行うことをいう。第四十七条の五第一項第二号において同じ。）の用に供する場合
三　前二号に掲げる場合のほか、著作物の表現についての人の知覚による認識を伴うことなく当該著作物を電子計算機による情報処理の過程における利用その他の利用（プログラムの著作物にあつては、当該著作物の電子計算機における実行を除く。）に供する場合
____

リバースエンジニアリングと一口にいっても、その対象・目的・程度によって見解はさまざまに分かれています。

* 対象による分類
** プラットフォーム
--- OSなどが該当します
--- 脆弱性などが見つかれば被害が拡大する、相互運用性がない場合範囲広くに影響する
-- 一般的なアプリケーション
- 目的による分類
-- 競合するソフトウェアの作成
--- インターフェースの解析によって相互運用性・相互接続性を高める→ユーザーのロックインを防ぐ効果
--- パクり
-- セキュリティ目的
--- 第1群
--- セキュリティ目的、というのがそもそも何であるのか
---- 学習、研究、脆弱性調査
-- 試験・研究目的
-- チート行為
-- その他(趣味など)
--- 一番気になるのが
-- 公共的な用途
--- 従来から認められている
- 程度による分類
-- 「第1群」
-- 「第2群」

=== 対象による分類

*プラットフォーム(基本ソフトウェア)* OSなどが該当します。

- その上で動作するアプリケーションに多大な影響をもたらす
- 技術競争を促進するため 特許法
-- 試験・研究目的での使用には特許法は適用されない(69条)
- ロックインを防ぐため 独占禁止法 
-- footnote:[丸山温道 (2007) 「著作権契約(リバースエンジニアリング)」　110ページ https://system.jpaa.or.jp/patents_files_old/200706/jpaapatent200706_106-110.pdf]

*一般的なアプリケーション* 

- プラットフォームとは違い影響範囲は小さいですが、相互運用性を高めるためのリバースエンジニアリングは問題ないとする見解が有力です。

=== 目的による分類

*試験・研究目的* 特許を得た発明を試験また研究のために利用する場合には特許権の効力は及びません(特許法第69条)。つまり、ソフトウェアの実装に特許の発明内容が含まれていたとしてもリバースエンジニアリングをしてもかまわないということです。

*チート行為のため* リバースエンジニアリングの手法等には関係なく、ゲームを有利に進めるためのチート行為は違法です。刑事事件として、私電磁的記録不正作出・同供用罪や電子計算機損壊等業務妨害罪が成立することがあります。また、「著作権者の利益を不当に害する」と判断されれば、著作権法の権利制限規定(第三十条の四ただし書きfootnote:[条文と中心となる内容を定めたあとに続く、「ただし」で始まる文のこと。例外を示す場合によく使われる。]など)においても権利制限の対象外となります。一方で、ゲームの記録を直接書き換えることなく、サービス側が公開していない新キャラなどの情報を解析によって獲得、SNSなどで拡散するリーク行為についての判例は見当たりませんでした。

*セキュリティ目的・その他趣味など* 次節で紹介する「第1層」に該当すると考えられます。

****

*「営業秘密」には該当するか？*

ITに関わる国家試験である情報技術者試験では、時折「*営業秘密*」についての問題が出ます。業務を進める上で有利となる研究データや、効率的な工場ラインのレイアウト、おいしい料理をつくるノウハウなどが営業秘密の例になります。一般生活では「企業秘密」という言い方もしますね。公表前のアイテムについての情報を「営業秘密」としてリーク行為から保護することは可能なのでしょうか。

営業秘密として認められるには、「秘密管理性」「有用性」「非公知性」の3つの要件を満たさなければなりませんfootnote:[特許とは違って、新規性などは条件になりません。]。

*秘密管理性* 秘密管理性を満たすには、秘密管理措置によって情報に触れる人から営業秘密であることがわかるようになっている必要があります(認識可能性)。経済産業省は「マル秘」印を書類に押す(伝統的な)方法のほかに、「ファイルへのパスワードの設定」などが秘密管理措置になりうるとしていますfootnote:keisan[経済産業省経済産業政策局知的財産政策室 営業秘密管理指針 (2019) 11ページ https://www.meti.go.jp/policy/economy/chizai/chiteki/guideline/h31ts.pdf]。ファイルの暗号化も同様だと考えられます。しかしながら、以下のようなシナリオで認識可能性が認められるかはわかりません。

* 公表前の情報がバイナリに含まれていて、そのパラメータとして設定されている公開日時が未来の日付である場合
* サーバにHTTPリクエストを飛ばす際にパラメータ経由で渡されるアイテムIDを書き換えて、IDに対応するアイテムが存在しないときは `404 Not Found` を返し、アイテムは存在するが公表前の場合は `403 Forbidden` を返す、ということをプレイヤーが経験則的に知った場合

ところで、ファイルそのものではなく、外部のサーバが設定しているパスワード等のアクセス制御を突破すれば、不正アクセス禁止法にひっかかります。

*非公知性* 情報が公に知られていない、または容易にアクセスできないという性質です。ソフトウェア以外を含むリバースエンジニアリングによって取得した情報の非公知性は、「特殊な技術をもって、相当な期間が必要であり、誰でも容易に当該情報を知ることができない場合には、非公知性要件を満たすことが認められる」というのが多数派の学説footnote:[陳珂羽「営業秘密の有用性と非公知性について -錫合金組成事件-」 (2018) 301ページ https://www.juris.hokudai.ac.jp/riilp/wp-content/uploads/sites/6/2019/01/52_08-%E5%88%A4%E4%BE%8B_%E9%99%B3%E7%8F%82%E7%BE%BD.pdf]です。とはいえ、その分野の専門家ではない裁判官に「特殊な技術」を用いたかどうかの判断ができるかどうかは微妙だと指摘する向きもありfootnote:[石本貴幸「営業秘密における有用性と非公知性について」 (2017) 121ページ https://system.jpaa.or.jp/patent/viewPdf/2774]、バイナリ解析や通信解析がどのように判断されるかはわかりません。

*有用性* 客観的にみて事業に有用であるかという性質です。最終的に失敗した研究のデータであっても「有用」とみなされます。一般に、秘密管理性と非公知性を満たす情報については有用性も認められますが、そうすることで公序良俗に反する場合footnote:[ 例えば企業の脱税に関する情報などを営業秘密として保護してしまうのは、ただの隠蔽ですよね]を除きますfootnote:keisan[]。

****

=== 程度による分類

この分類は2018年の著作権法改正によって大きく変化しました。権利関連でよく用いられる「権利制限」という言葉については、権利者(開発者)と使用者(リバースエンジニアリングがしたい人)のどちらの権利を制限するのか混乱しないように気をつけて読み進めるのがコツです。ここでは「権利制限」は「開発側の権利を制限して、使用者に権利を与える」という意味で用います。

文化庁から、著作権法改正についての資料footnote:[文化庁長官官房著作権課「著作権法の一部を改正する法律案　概要説明資料」 (2018) https://www.kantei.go.jp/jp/singi/titeki2/tyousakai/kensho_hyoka_kikaku/2018/sangyou/dai5/siryou2-4.pdf]がリリースされています。「ＡＩ、ＩｏＴ、ビッグデータを活用したイノベーションを創出しやすい環境を整備し、『第４次産業革命』を加速」するそうです。資料では、改正著作権法によって認められる利用の程度を「層」によって区別しています。「層」はそれぞれの条文に対応します。

改正のモチベーションとしては、「第4次産業革命やりたいけど、今後も法改正するの面倒だしまとめてOK出しちゃえ」という感じでしょうか。これまで個別の条文で対応していた第1層、第2層について、新30条の4と新47条の4,5で包括的に権利制限を規定すると同時に、権利制限の対象が大きく広がることになりました。

*第1層* 権利者の損害がない
--- 「著作物に表現された思想又は感情の享受を目的としない利用」
---- たとえば本を読んで著者の主張を知ったり、キャラクターのイラストを見て「カッコいいなあ」と思ったりするのは「思想又は感情の享受を目的とした」利用と言えます
---- 対して、学習用にクローラで集めてきたデータを機械学習に用いても、学習モデルが思想を理解することはない(現状ではそういうことになってますよね)ので、許諾を得ずに使ってもいいよ、ということだと考えられます
---- もちろん、リバースエンジニアリング中に「この実装ヤベえ」という感情を得ることはありますが、それは「著作物に表現された」ものとはいえないはずです。

「包括的な」規定によって、リバースエンジニアリングに加え、CDNでのキャッシュや機械学習用の学習データ収集にも権利制限が認められました。資料では「サイバーセキュリティ確保等のための」リバースエンジニアリングと説明していますが、条文でこれに限定しているわけではありません。

---- 条文では「情報解析」と書かれていますが、これは機械学習向けの項目で、リバースエンジニアリングについては「その他の」という30条の4の文字列で権利制限がかかることになっています。
---- バスケット条項もリバースエンジニアリング向けではない
-- *第2層* 権利者の損害が軽微
--- 以前は検索エンジンのみ(descriptionの自動生成とかですよね)
--- 所在検索サービス
--- 情報解析サービス
--- 「新たな知見又は情報を創出し、及びその結果を提供する行為であつて、国民生活の利便性の向上に寄与するもの」(バスケット条項)
-- *第3層* 権利者の権利と衝突するが、公の利益になる利用
--- 引用や図書館での利用が広く知られています
--- 改正によって障害者向けのやアーカイブ
--- 引き続き法令によって個別に権利制限を加える

== 法令と利用規約

*法令* 国会が定める法律だけではなく、行政機関が定める政令・規則を含んで「法令」と呼びます。刑事罰が定められている場合があります。著作権法の改正により、リバースエンジニアリングが合法であることが示されたと考えられています。

*利用規約*

- サービス利用開始時に同意を求められる利用規約・EULA等ライセンス契約の類
-- 該当する行為が合法であっても、サービス側から同意を求められる利用規約において、多くの場合リバースエンジニアリングが禁止されています。そして、有効な契約条項への違反(債務不履行)に対しては損害賠償の請求が認められています。
-- 利用規約は契約なのか
-- 「同意」を押せば契約が成立するのか
-- 利用規約に同意する前にリバースエンジニアリングを行えば禁止事項には引っかからないのではないか

- 法令と利用規約の関係について
-- 契約自由の原則
--- 特段の定めがない場合、契約は法令に優先する
--- 法令で定められた内容を、契約で書き換えることができる(オーバーライド)
-- ただし原則には例外がつきもの
-- 「任意規定(任意法規)」と「強行規定(強行法規)」
--- いわゆる法律用語だが、条文中で直接これらの表現が使われているわけではない
--- 条文が任意規定ならば、契約自由の原則にのっとって契約で指定した内容が優先されます
--- 強行規定ならば、契約自由の原則は適用されず、契約のうち強行規定に反する部分は無効になります
-- 強行規定は条文で「これは強行規定ですよ」と示されていないのがやっかいなところ
--- 強行規定は公の秩序に関する規定、という判断基準がある

以下はIPAの資料からの引用ですfootnote:[独立行政法人情報処理推進機構 (2019) 「情報システム等の脆弱性情報の取扱における法律面の調査 報告書改訂版」] 12ページ https://www.ipa.go.jp/files/000072543.pdf]。

[quote]
____
そして、この権利者の利益を通常害さないと評価できる行為類型の代表例として、「セキュリティ確保のためのソフトウエアの調査解析等」があげられている。これにより、脆弱性調査のためのリバース・エンジニアリング行為が著作権法上禁止されているのではないかという問題については、決着をみたものと考えられる。もっとも、ライセンス契約におけるリバース・エンジニアリング禁止の効力が、脆弱性情報調査に対しても有効なのか、という問題は、依然として存在している。
____


--- 
- ただし、利用規約でリバースエンジニアリングが禁止されている場合、法律と利用規約のどちらが優先されるかはわからない
- 著作権法第三十条の四などがどちらに属するものかは確定していない
-- 競争法の立場から、リバースエンジニアリングによって競争が加速する(公の秩序に貢献する)という見方
-- 判例の積み重ねを待つしかない

- 海外でのリーク行為
-- 韓国版ミリシタでのリーク
--- 韓国では日本よりもリバースエンジニアリングに対して明確に寛容な立場を取っている <<1>>



-- 対して、チートでないリバースエンジニアリングについては
--- 著作権法
---- 強行規定と任意規定
--- 独占禁止法
--- 消費者契約法
--- 民法
---- シュリンクラップ契約
---- 契約がそもそも成立しているか
- この記事について

- 「法令適用事前確認手続(ノーアクションレター制度)」は民間企業など国民が、法に触れる心配のある行いをしようとするときに、法令を所管する省庁に直接問い合わせる制度です。
-- 1ヶ月程度で回答が返ってくるようです。問い合わせ先によっては氏名や住所の公表について同意を求める欄もありますが、同意しなければ公表されず、回答のみが公表されるようですfootnote:[「文部科学省における法令適用事前確認手続に係る照会書」 http://www.mext.go.jp/component/b_menu/other/__icsFiles/afieldfile/2012/09/21/1326070_1.pdf]。
-- それぞれの省庁のWebサイトにおいて、対象となる所管法令についての窓口が示されている
-- 著作権法を所管するfootnote:[「所管の法令等
」 http://www.bunka.go.jp/seisaku/bunka_gyosei/shokan_horei/index.html]文化庁ではそもそも手続に関するページがない
-- 親玉となる文部科学省では問い合わせ先が一覧になっており、「著作権課」も含まれているものの、著作権法についての問い合わせは受け付けていないfootnote:[「文部科学省における法令適用事前確認手続について」 http://www.mext.go.jp/b_menu/toukei/005/020401.htm]。
-- 消費者庁は手続きを受け付け、消費者契約法が所管であるfootnote:[「所管の法令等
」 https://www.caa.go.jp/law/laws/]が、やはりリバースエンジニアリング禁止条項に関係するであろう第10条の問い合わせ先は掲載されていないfootnote:[「各法律の条項との問い合わせ先一覧」 https://www.caa.go.jp/law/nal/pdf/b_ichiran_180330_0001.pdf]。
-- 類似の制度である「グレーゾーン解消制度」は、事業を始めようとする人が対象であり、事業内容の提出などを求められる。


- 2019年1月1日に改正著作権法が施行されました。
- 独占禁止法
- 実は結構前から議論されている
-- 改正前の条文に対しても、

http://www.bunka.go.jp/seisaku/chosakuken/hokaisei/h30_hokaisei/
- 改正著作権法
		[●100●知財研紀要  2006 17  コンピュータ・プログラムの保護に関する 米・EU・日・韓の比較法的研究 －プログラム  リバース・エンジニアリングを中心に－ http://www.iip.or.jp/pdf/fellow/detail05j/17_17.pdf]
			EUディレクティブ→許可
			US→フェアユース
			韓国→許可に近い
		http://www.j.u-tokyo.ac.jp/jjweb/research/MAR2002/sakuma_hisashi.pdf
		http://www.it-houmu.com/archives/1514
			利用規約違反の場合でも違約金などは消費者契約法によって制限される
	https://www.kantei.go.jp/jp/singi/titeki2/tyousakai/kensho_hyoka_kikaku/2018/sangyou/dai5/siryou2-4.pdf
		３ページ目の「第1層」「第２層」


http://www.mext.go.jp/b_menu/shingi/bunka/gijiroku/013/06073103/002.htm
http://www.j.u-tokyo.ac.jp/jjweb/research/MAR2002/sakuma_hisashi.pdf 17ページ


- ミリシタの利用規約でもリバースエンジニアリングは禁止されている
- よってこの記事も利用規約から見ればグレー(民法上のリスクがある)
- しかしながら、リバースエンジニアリングをハードウェアやソフトウェアに対して行った資料が商用・非商用にかかわらずちらほら見かけるので、どうなるのか気になっている
-- みんなで渡れば怖くない、と正当化する意図はない
- ほとんどテンプレのような形でリバースエンジニアリングを禁止する条項が設定されているので、結局改正の意味がないのでは

== おわりに

- いちいち「パイシュー生地事件」とか名付けてて笑っちゃう
- 自然言語で書かれた法令に対しては、RFCやソースコードとはまた違う読み方をする必要があり骨が折れつつも、「こんな場合はどうなんだろう？」と読み進めるのは楽しかったです。信義則はあいまいさの象徴ですよね。