= リバースエンジニアリングと法律

[.text-right]
sei0o (@sei0o, 部長) +
 +

　「リバースエンジニアリング」は誰かが開発したモノを分解・解析することですfootnote:[対義語として「フォワードエンジニアリング」が存在し、アプリやサービスを開発することを指します。もっとも、この語自体はリバースエンジニアリングの文脈でしか見かけることがないのですが…]。先行する製品の仕組みを理解したり、ソフトウェア内部で使用しているライブラリを見つけたり、ただ使用するだけでは得られない様々な情報を知ることができます。しかしながら、ゲームに対するチート行為の手段としても悪用されやすいという一面もあります。この記事では、改正著作権法の施行をきっかけに、そんなリバースエンジニアリングを行う上で深い関わりを持つ法律についてまとめました。

　筆者は法曹ではなくただの心配性な素人であり、以下の記述は公的機関・研究機関・弁護士が公開している資料や判例を素人の観点で読んで得た知識から構成されています。末尾に示した参考文献を適宜参照することをおすすめします。

== リバースエンジニアリングの分類

　リバースエンジニアリングと一口にいっても、その対象・目的によって見解はさまざまに分かれています。

=== 対象による分類

　リバースエンジニアリングという語そのものはソフトウェアに限らず自動車や軍事の分野でも使われていますが、本文では対象をソフトウェアに限定します。

一般的なアプリケーション:: 互換性を高めるためのリバースエンジニアリングは問題ないとする見解が有力です。

プラットフォーム(基本ソフトウェア):: OSなどが該当します。アプリケーションの実装はプラットフォームが提供するAPI等に大きく影響され、ユーザがソフトウェアを購入する際の選択肢も端末のOSによって絞られます。プラットフォームの開発者があえてクローズドなAPIのみを提供したり、自社製品にのみ特別な動作ができるように制限を加えたりした場合でも、それらに依存しているアプリ開発者とそのユーザは不便を受け入れざるを得ません(ロックイン)。ゆえに、独占禁止法の観点から、特にプラットフォーム間の互換性の確保のためのリバースエンジニアリングは許されるべきだ、という学説がありますfootnote:maruyama[丸山温道 (2007) 「著作権契約(リバースエンジニアリング)」　110ページ https://system.jpaa.or.jp/patents_files_old/200706/jpaapatent200706_106-110.pdf]footnote:sakuma[佐久間央 (2002) 「契約面から見た財産的情報 ～禁止条項の有効性を中心として～」 17ページ http://www.j.u-tokyo.ac.jp/jjweb/research/MAR2002/sakuma_hisashi.pdf]footnote:[文部科学省 (2006) 「文化審議会著作権分科会法制問題小委員会 契約・利用ワーキングチーム検討結果報告」 http://www.mext.go.jp/b_menu/shingi/bunka/gijiroku/013/06073103/002.htm]。

=== 目的による分類

試験・研究:: 特許を得た発明を試験また研究のために利用する場合には特許権の効力は及びません(特許法第69条)。つまり、ソフトウェアの実装に特許の発明内容が含まれていたとしてもリバースエンジニアリングをしてもかまわないということです。ただし、解析で見つけた発明内容を使って新たに何かソフトウェアを作るのは特許権の侵害になるおそれがあります。特許法第69条や半導体回路配置保護法第12条の2・回路配置利用権の制限規定における考え方を適用してリバースエンジニアリングが適法だとする主張もありますfootnote:maruyama[]。

チート:: 「チート」行為の文脈でも、不正に書き換えるパラメータ等を特定するために、リバースエンジニアリングは使用されています。チートを目的とするリバースエンジニアリングを直接制限する法律はありません。とはいえ最終的なチート行為に対して、民事上の損害賠償を求められ、刑事事件として私電磁的記録不正作出・同供用罪や電子計算機損壊等業務妨害罪が適用されたことがありますfootnote:[AKIBA PC Hotline! (2015) 「チートツール販売で有罪判決。懲役2年、執行猶予4年」 https://akiba-pc.watch.impress.co.jp/docs/eswatch/722031.html]。また、「著作権者の利益を不当に害する」と判断されれば、後述する著作権法の権利制限規定(第三十条の四ただし書きfootnote:[条文と中心となる内容を定めたあとに続く、「ただし」で始まる文のこと。例外を示す場合によく使われる。]など)においても権利制限の対象外となります。一方で、ゲームの記録を直接書き換えることなく、サービス側が公開していない新キャラなどの情報を解析によって獲得、SNSなどで拡散するリーク行為についての判例は見当たりません。

セキュリティ・その他趣味など:: 次節で紹介する改正著作権法での「第1層」に該当すると考えられます。

== 改正著作権法

　この分類は2018年の著作権法改正によって大きく変化しました(施行は2019年1月1日)。権利関連でよく用いられる「権利制限」という言葉については、権利者(開発者)と使用者(リバースエンジニアリングがしたい人)のどちらの権利を制限するのか混乱しないように気をつけて読み進めるのがコツです。ここでは「権利制限」は「開発側の権利を制限して、使用者に権利を与える」という意味で用います。

　文化庁から、著作権法改正についての資料footnote:[文化庁長官官房著作権課  (2018) 「著作権法の一部を改正する法律案　概要説明資料」 https://www.kantei.go.jp/jp/singi/titeki2/tyousakai/kensho_hyoka_kikaku/2018/sangyou/dai5/siryou2-4.pdf]がリリースされています。曰く、「ＡＩ、ＩｏＴ、ビッグデータを活用したイノベーションを創出しやすい環境を整備し、『第４次産業革命』を加速」するそうです。資料では、改正著作権法によって認められる利用の程度を「層」によって区別しています。「層」はそれぞれの条文に対応します。

　改正のモチベーションとしては、「第4次産業革命やりたいけど、あとから法改正するの面倒だしまとめてOK出しちゃえ」という感じでしょうか。これまで個別の条文で対応していた第1層、第2層について、新30条の4と新47条の4,5で包括的に権利制限を規定すると同時に、権利制限の対象が大きく広がることになりました。リバースエンジニアリングと直接関係するのは第1層ですが、その他も併せて紹介しておきます。

.未公開情報は「営業秘密」に該当するか？
****
　ITに関わる国家試験である情報処理技術者試験では、時折不正競争防止法で規定されている「*営業秘密*」についての問題が出ます。業務を進める上で有利となる研究データや、効率的な工場ラインのレイアウト、おいしい料理をつくるノウハウなどが営業秘密の例になります。一般生活では企業秘密という言い方もしますね。

　では、公表前のゲームアイテムなどについての情報を営業秘密としてリーク行為から保護することは可能なのでしょうか。ある情報が営業秘密として認められるには、「秘密管理性」「有用性」「非公知性」の3つの要件を満たさなければなりません。

　*秘密管理性* を満たすには、秘密管理措置によって情報に触れる人から営業秘密であることがわかるようになっている必要があります(認識可能性)。経済産業省は「マル秘」印を書類に押す伝統的な方法のほかに、ファイルへのパスワードの設定(暗号化)やアクセス制御が秘密管理措置になりうるとしています。たとえ秘密管理措置が不十分(パスワードが書かれた付箋をPCに貼っているなど)でも、「常識的に漏らしちゃいけないってわかるよね」として秘密管理性が認められた判例がありますfootnote:keisan[経済産業省経済産業政策局知的財産政策室 (2019) 「営業秘密管理指針」 9〜11ページ https://www.meti.go.jp/policy/economy/chizai/chiteki/guideline/h31ts.pdf]。以下のようなシナリオでも、秘密管理性が認められるかもしれません。

* ソフトウェア本体に含まれていた、ある情報のパラメータとして設定されている公開日時が未来の日付であり、少なくともそれが未公開情報であることは認識できる場合
* サーバにHTTPリクエストを飛ばす際にパラメータ経由で渡されるアイテムIDを書き換えて、IDに対応するアイテムが存在しないときは `404 Not Found` を返し、アイテムは存在するが公表前の場合は `403 Forbidden` を返す、というレスポンスのパターンから未公開の新アイテムが存在していると知った場合

　ところで、ファイルそのものではなく、外部のサーバが設定しているパスワード等のアクセス制御を突破すれば、不正アクセス禁止法が関係してきます。

　*非公知性* は、情報が公に知られていない、または容易にアクセスできないという性質です。情報をリバースエンジニアリングによって取得した場合については、「特殊な技術をもって、相当な期間が必要であり、誰でも容易に当該情報を知ることができない場合には、非公知性要件を満たすことが認められる」というのが多数派の学説footnote:[陳珂羽　(2018) 「営業秘密の有用性と非公知性について -錫合金組成事件-」 301ページ https://www.juris.hokudai.ac.jp/riilp/wp-content/uploads/sites/6/2019/01/52_08-%E5%88%A4%E4%BE%8B_%E9%99%B3%E7%8F%82%E7%BE%BD.pdf]となっています。とはいえ、その分野の専門家ではない裁判官に「特殊な技術」を用いたかどうかの判断ができるかどうかは微妙だと指摘する向きもありfootnote:[石本貴幸 (2017) 「営業秘密における有用性と非公知性について」 121ページ https://system.jpaa.or.jp/patent/viewPdf/2774]、バイナリファイルや通信の解析がどのように判断されるかはわかりません。

　*有用性* は、客観的にみて事業に有用である場合に認められます。最終的に失敗した研究のデータなどであっても「有用」とみなされます。一般に、秘密管理性と非公知性を満たす情報については有用性も認められますが、そうすることで公序良俗に反する場合は除かれますfootnote:keisan[]。例えば、企業の脱税に関する情報を営業秘密として保護してしまうのは、ただの隠蔽であり、公序良俗に反するといえます。

　以上を踏まえると、リバースエンジニアリングが絡む場合はまず非公知性が争点になると思われます。非公知性が認められた場合、もしくはリバースエンジニアリング以外の方法で情報を得た場合には秘密管理性が問われると考えられます。

****

=== 第1層(権利者の損害がない)

　著作権法第30条の4「著作物に表現された思想又は感情の享受を目的としない利用」および第47条の4「電子計算機における著作物の利用に付随する利用等」によって権利制限が規定されます。リバースエンジニアリングはこの層に属しています。以下に条文を引用します。

[quote]
____
[%hardbreaks]
（著作物に表現された思想又は感情の享受を目的としない利用）
第三十条の四　著作物は、次に掲げる場合その他の当該著作物に表現された思想又は感情を自ら享受し又は他人に享受させることを目的としない場合には、その必要と認められる限度において、いずれの方法によるかを問わず、利用することができる。ただし、当該著作物の種類及び用途並びに当該利用の態様に照らし著作権者の利益を不当に害することとなる場合は、この限りでない。

[%hardbreaks]
一　著作物の録音、録画その他の利用に係る技術の開発又は実用化のための試験の用に供する場合
二　情報解析（多数の著作物その他の大量の情報から、当該情報を構成する言語、音、影像その他の要素に係る情報を抽出し、比較、分類その他の解析を行うことをいう。第四十七条の五第一項第二号において同じ。）の用に供する場合
三　前二号に掲げる場合のほか、著作物の表現についての人の知覚による認識を伴うことなく当該著作物を電子計算機による情報処理の過程における利用その他の利用（プログラムの著作物にあつては、当該著作物の電子計算機における実行を除く。）に供する場合
____

　「思想又は感情の享受」というのは、たとえば本を読んで著者の主張に納得したり、キャラクターのイラストを見て「カッコいいなあ」と楽しんだりすることですfootnote:[早稲田大学知的財産法制研究所 (2018) 「著作物に表現された思想又は感情の享受(桑原俊)」 https://rclip.jp/2018/05/29/201806column/]。対して、学習用にクローラで集めてきたデータを機械学習に用いても、学習モデルが思想を理解して、知的欲求を満たすことはない(現状ではそういうことになってますよね)ので、使ってもいいよ、ということだと考えられます。もちろん、リバースエンジニアリング中に「この実装ヤベえ…」という気持ちになることはありますが、それは「著作物に表現された」感情とはいえないはずです。

　「包括的な」規定によって、リバースエンジニアリングに加え、CDNでのキャッシュや機械学習用の学習データ収集にも権利制限が認められました。資料では「サイバーセキュリティ確保等のための」リバースエンジニアリングと説明していますが、条文でこれに限定しているわけではなさそうです。

　第30条4の各号の例(「次に掲げる場合」)には「情報解析」がありますが、これは機械学習向けの項目です。また、「前二号に掲げる場合のほか、」で始まる第3号も、リバースエンジニアリング向けの記述ではありません。リバースエンジニアリングについては第30条4の「その他の」という部分で該当することになっています。

　ところで、著作権のなかでも、リバースエンジニアリングに適用される権利制限規定によって制限される権利には、複製権と翻案権が挙げられます。前者は実行中にSSDからメモリにプログラムをロードすることに、後者は逆アセンブルによって機械語からアセンブリを抽出することに対応します。当然プログラムを実行しただけで著作権の侵害となっては困るので、前者については第47条の3で権利制限がかけられています。

=== 第2層(権利者の損害が軽微)

　著作権法第47条の5「新たな知見・情報を創出する電子計算機による情報処理の結果提供に付随する軽微利用等」によって権利制限が規定されます。

　「軽微利用」というのは、検索結果などで著作物の一部を使用する場合を指します。改正前は旧47条の6によって、「インターネット上を対象とする」検索エンジンがサイトの内容から検索ワードに合致する文章を自動で取ってくる場合などに権利制限が認められていました。主に、所在検索サービス(対象をインターネット上の情報に限定しない検索エンジン)、情報解析サービス(口コミ分析など)にでの著作物利用に適用されます。

=== 第3層(権利者の権利と衝突するが、公の利益になる)

　引用や図書館での利用はこれにあたります。改正によって障害者への対応やアーカイブ事業に対して権利制限が加えられました。第1・2層とは異なり権利者にそれなりに大きな損害を与える可能性があるので、引き続き法令によって個別に権利制限を定める方針となっています。

== 法令と利用規約

　国会が定める法律だけではなく、行政機関が定める政令・規則を含んで *法令* と呼びます。著作権法の改正により、リバースエンジニアリングは合法であると明示されたと考えられます。

　しかしながら、多くの場合 *利用規約* においてリバースエンジニアリングは禁止されています。サービス利用開始時に同意を求められるアレです(EULA等も以下「利用規約」で統一します)。スマホに入っているアプリの利用規約を開いてみると、以下のような文言が見当たるのではないでしょうか。

[quote]
____
[%hardbreaks]
第○条 お客様は、以下に示された行為を行ってはなりません。
  (iv) 本サービスが提供するソフトウェア等のリバースエンジニアリング(逆コンパイル、逆アセンブルを含む)。
____

　有効な契約条項への違反(債務不履行)に対しては限度付きで違約金の請求やアカウント停止(BAN)などの措置が認められていますfootnote:seisai[高岡晃士 (2017) 「利用規約違反に対する制裁に関する問題」 http://www.it-houmu.com/archives/1514]。しかし、「利用規約に同意する」ボタンを押さないままリバースエンジニアリングを行えば違反にならないのでは、といった疑問もあります。

　法令と利用規約の関係も一筋縄ではいきません。*「契約自由の原則」* により、契約は法令に優先することになっています。つまり、法令で定められた内容を契約で書き換えることができます(*オーバーライド*)。それにもかかわらず、以下のIPAの資料によればfootnote:[独立行政法人情報処理推進機構 (2019) 「情報システム等の脆弱性情報の取扱における法律面の調査 報告書改訂版」 12ページ https://www.ipa.go.jp/files/000072543.pdf] (強調は筆者によるもの)、たとえリバースエンジニアリングを利用規約で禁止した場合においても、その条項が有効なのかは断定できないようです。どうしてでしょうか？

[quote]
____
そして、この権利者の利益を通常害さないと評価できる行為類型の代表例として、「セキュリティ確保のためのソフトウエアの調査解析等」があげられている。これにより、脆弱性調査のためのリバース・エンジニアリング行為が著作権法上禁止されているのではないかという問題については、決着をみたものと考えられる。_もっとも、ライセンス契約におけるリバース・エンジニアリング禁止の効力が、脆弱性情報調査に対しても有効なのか、という問題は、依然として存在している。_
____


　原則には例外がつきものだ、ということですね。実は法令の条文には *「任意規定(任意法規)」* と *「強行規定(強行法規)」* の2種類が存在します。条文が任意規定ならば、上で示した通り、契約自由の原則に沿って契約で指定した内容が優先されます。対して強行規定ならば、条文が契約より強い力を持ち、契約のうち強行規定に反する部分は無効になります。シンプルにまとめると「強行規定＞契約＞任意規定」と表せます。いわゆる法律用語ですが、条文中で直接これらの表現が使われているわけではなく、しかも条文で「これは強行規定ですよ」とほぼ示されていないのがやっかいなところです。代わりに「公の秩序に関するものは強行規定」、別の言い方をすれば「公の秩序に反する契約の条項は無効」という判断基準が用いられ、その判断は裁判所が下すことになります。改正著作権法第30条の4については、判例がまだないために、強行規定・任意規定のどちらであるか確定していません。

　仮に第30条の4が任意規定であったとしても、リバースエンジニアリング禁止条項は他の法律に反しているため無効であるとの説がありますfootnote:sakuma[]footnote:[鄭鎭根 (2006) 「コンピュータ・プログラムの保護に関する 米・EU・日・韓の比較法的研究 －プログラム  リバース・エンジニアリングを中心に－」 104ページ http://www.iip.or.jp/pdf/fellow/detail05j/17_17.pdf]。先に述べたとおり、競争が不正に妨げられるとなれば独占禁止法によって条項は無効になります。そして消費者契約法第10条では、任意規定をオーバーライドした条項であっても、民法の信義則に反し消費者の利益を一方的に害するものは無効であるとされていますfootnote:[消費者庁 (2019) 「不当な契約は無効です！ -早わかり！消費者契約法-」 https://www.caa.go.jp/policies/policy/consumer_system/consumer_contract_act/public_relations/pdf/public_relations_190401_0001.pdf]。

.わからないなら聞いてみよう
****
　*「法令適用事前確認手続(ノーアクションレター制度)」* は民間企業など国民が、法に触れるかもしれない行為をしようとするときに、法令を所管する省庁にメールで質問ができる、電話が苦手な筆者にもやさしい制度です。対象となる各法令を管轄する省庁のWebサイトにて窓口が示されています。氏名や住所の公表について同意を求められることがありますが、断っても回答されますfootnote:[文部科学省「文部科学省における法令適用事前確認手続に係る照会書」 http://www.mext.go.jp/component/b_menu/other/__icsFiles/afieldfile/2012/09/21/1326070_1.pdf]。

　せっかくなのでリバースエンジニアリングについて聞いてみようしたところ、この制度で質問できる法令は限られていました。著作権法を所管するfootnote:[文化庁「所管の法令等
」 http://www.bunka.go.jp/seisaku/bunka_gyosei/shokan_horei/index.html]文化庁ではそもそも手続に関するページがありません。その親玉となる文部科学省では問い合わせ先が一覧になっており、「著作権課」も含まれているものの、著作権法についての問い合わせは受け付けていませんfootnote:[文部科学省「文部科学省における法令適用事前確認手続について」 http://www.mext.go.jp/b_menu/toukei/005/020401.htm]。消費者庁は消費者契約法を所管していますfootnote:[消費者庁「所管の法令等
」 https://www.caa.go.jp/law/laws/]が、やはりリバースエンジニアリング禁止条項に関係するであろう第10条の問い合わせ先は掲載されていませんfootnote:[消費者庁「各法律の条項との問い合わせ先一覧」 https://www.caa.go.jp/law/nal/pdf/b_ichiran_180330_0001.pdf]。類似の制度に「グレーゾーン解消制度」がありますが、こちらは事業を始めようとする人が対象であり、事業内容の提出などを求められます。

****


== おわりに

　もともとこの「リバースエンジニアリングと法律」は、リバースエンジニアリングを紹介するための別記事のコラムとして書くつもりでしたが、いろいろ調べてメモしているうちに随分な長さになってしまったので独立した記事としてまとめました。参考文献の出版年からわかる通り、このテーマは実は結構前から議論されているようです。

　筆者はリバースエンジニアリングをかじった一個人として、「別に逆コンパイルぐらいええやん」という立場です。ゲームからキャラクターの3Dモデルを抽出してニコニコにアップロードするなどはさすがに一考すべきですが、単純にどのような仕組みで動いているのか学習・研究する分には認められてほしいと思っています。改正著作権法によって刑事罰のリスクはほぼなくなったので、利用規約のグレーゾーンにおける民事訴訟リスクを減らしながら動くのがよさそうです。法改正前と同じく「黙認」に落ち着くかもしれません。

　話はそれますが、様々なサービスの利用規約では、ほとんどテンプレのような形でリバースエンジニアリングの禁止規定が設定されているように思えます。Webサイトの利用規約に「逆アセンブル、逆コンパイルその他これに類する行為を禁じます」と書かれても、「いやいや、WebAssemblyないのにどうやって逆コンパイルするんですか？」と言いたくなってしまいます。仮にこの規定が制限なく有効であると判断が下されれば、「第1層」の改正の効果が薄くなるのでそこは気がかりです。ハードウェアやソフトウェアの解析資料は同人誌即売会でもちらほら見かけますし。

　一般の感覚からすれば、事件というのは刑事事件を想起しますが、法律の世界では民事訴訟なども事件と呼ぶようです。参考文献でもいちいち「パイシュー生地事件」footnote:[不正競争防止法判例データベース 「平成 14年 (ワ) 162号 売買代金等請求事件」 http://husei.hanrei.jp/hanrei/uc/2598.html]などと名付けていてシュールでした。あいまいさを含む自然言語で書かれた法令に対しては、ソースコードとはまた違う読み方をする必要があり、骨が折れつつも、「こんな場合はどうなんだろう？」と考えながら読み進めるのは楽しかったです。この記事がリバースエンジニアリングにおいての法律理解の一助となれば嬉しいです。

'''