version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby

    steps:
      - checkout
      - run:
          name: Install Gems
          command: bundle install
      - run:
          name: Create PDF
          command: bundle exec rake