= 自動選曲の真実
:mermaid: 
:xrefstyle: short

[.text-right]
sei0o （@sei0o, 部長） +
 +

　初心者から企業まで幅広い人気を誇るゲームエンジンUnityfootnote:[ゲームを製作するのに物理演算などの機能をパッケージにしたものをゲームエンジンといいます。Unityはそういったパッケージ以外に、開発環境（IDE）も提供しています。]で作成されたゲームのリバースエンジニアリングを通じて、ゲームの裏方で使われている技術についての理解を深める記事です。いわゆるチュートリアルではなく、読み物もしくは概要として書いていますので、詳細な手順は省略していますfootnote:[チートへの転用も避けたいというのが表向きの理由で、執筆が間に合わなかったというのが本音です。]。

== 解析対象について

　解析の対象とするのは、たまたま手持ちの端末に入っていたFree to Playの音楽ゲームです。iOS, Androidに対応しています。度重なるアップデートで曲数が増え、曲を選ぶのが大変になってきたところに、自動選曲機能が追加されました。開発者のアップデートコメントには、「ゲーム内のキャラクターが曲を選んでくれる」とあります。そりゃすごい。しかし、ここで疑問が生まれます。

　キャラクターは本当に曲を選んでくれているのでしょうか？

　数万を越えるアクティブユーザのそれぞれに対して最適な曲を提案するのは至難の業です。コメントの内容が本当かどうか確かめてみるべきではないでしょうか。最近流行りのファクトチェックです。これを解析の目標とします。

　対象のアプリがどういったゲームエンジンで動いているかは、ライセンス情報から推測可能です。今回はJSONの処理ライブラリ等の他に、DOTweenというライブラリの表記が見つかりました。DOTweenはUnity上で動作するアニメーション用のアセットfootnote:[Unityではライブラリや素材のことをアセットと呼び、ユーザが公開したものをアセットストアから購入できるようになっています。]です。逆に言えば、これが含まれているということはアプリがUnity製であるとわかります。

== Unityゲームの内部構造

　Unityでの開発にはC#がよく用いられます。ソースコードがゲームになるまでの変換の流れが<<entire-view>>です。

[mermaid, entire-view, png, width=400]
[#entire-view]
.全体像
----
graph LR
C# --> |Mono| IL
IL --> |IL2CPP| C++
C++ --> |compiler| .ipa/.apk
---- 

　C#はMonoのコンパイラによって一度IL（Intermediate Language, 中間言語）に変換されます。通常であればこのILをランタイム（CLR）に渡せばプログラムは動作しまがが、このILには「もとのC#のソースコードを容易に復元可能である」という弱点があります。また、ILを実行時に変換することによじ実行速度への影響も無視できません。そのため、あえてILをC++を通しCPUネイティブの機械語にしてしまう、という手法が取られています。そこで用いられるのがIL2CPPです。

　変換された機械語はそのままではなく、iOSであればIPA・AndroidであればAPKといった形式のファイルに格納されます。これらの形式の実体はただのZIPですので、一般のユーザでも容易に中身を見ることができます。

　解析する方法は対象をどのレイヤで見るかによって様々です。<<methods>>にいくつかのレイヤと、それらに対応する手法を例示します。

[#methods]
.解析の方法いろいろ
|===
|レイヤ|方法|ツール
|機械語のプログラム（バイナリ）|逆コンパイル・逆アセンブル|Ghidra, IDA
|スマホアプリ|コード注入|Frida, デバッガ
|iOS|Method Swizzling|Cycript, MachOViewer, classdump, dumpdecrypted
|Unity||アセット取り出し系ツール
|IL2CPP|global_metadataの利用|Il2CppDumper
|===

== IL2CPP

　先述した通り、IL2CPPはILをC\+\+に変換するソフトウェアです。この結果を元にして生成されたバイナリから、もとのILを復元することは実質的には不可能になります。しかしながら、逆コンパイラとIl2CppDumperなどを使用することで、どのようなC\+\+コードが間に存在していたかはある程度把握することができます。

== ツールに頼る

　とりあえず、先人が作ったツールをありがたく使わせていただいて、やれるところまでやってみましょう。

=== アプリをコピーしてくる

　アプリそのものがないことには何も始まらないので、端末からコピーしてきます。iOSでは暗号化された状態で保存されているアプリを復号してからコピーする必要があります。dumpdecryptedやCrackerXIがやってくれます。

== Ghidraで開いてみる

　GhidraはNSAが昨年公開したオープンソースのソフトウェア解析環境です。Ghidraの登場により、高性能な逆コンパイラが自由に使えるようになりましたfootnote:[筆者もGhidraの登場までは逆アセンブラを使って動作を追っていました。x86系ばかりを読んでいたので、スマートフォンで一般的なARMアセンブリの構文はほとんどわかりませんが…]。Ghidraそのものの解説は「Ghidra Pro Book」が詳しいです。

== Ghidraスクリプトを書く

　Ghidraは他の逆コンパイラ同様、ユーザがスクリプトを書いて操作を自動化・機能を拡張できるよう仕組みを備えています。スクリプトはPythonとJavaに対応しています。公式のサンプルで提供されているのはJavaですが、ここではPythonを用いますfootnote:[Ruby対応してくんねえかな〜]。


== 関数を探す

== おわりに