= 部誌 2019
:author: 明石高専情報工学研究部
:doctype: book
:toc-title: 目次
:toc:
:sectnums:
:chapter-label:
:lang: ja
:figure-caption: 図
:table-caption: 表
:example-caption: 例
:stem: latexmath

[preface]
== はじめに

　明石高専情報工学研究部 （情研） 部長の sei0o です。今年の部誌では記事1本の執筆と編集を担当しました。ここ数年、「技術系同人誌」と言われるものが技術者界隈で流行っています。技術者のコミケとも呼ばれる「技術書典」の名前を耳にしたことがあるかもしれません。

　実は、かつて情研にも似た文化が存在していたことが、部室の発掘調査によりわかってきました。本棚の隅にある日焼けしたバインダーの背には「研究発表会」と書かれています。中の紙面には、学年関係なく過去の部員がモータの動かし方などを記しています。大小様々なフロッピーディスクも挟まっています。このアウトプットは技術系同人誌ブームの先取りともいえるわけで、これを復活させる形で部誌を書くのはどうだろう、という発想が生まれました。

　簡単に情研の活動内容を紹介します。詳しい内容はWebサイトfootnote:[http://jyoken.net]を参照してください。情研はその下にいくつか班を持っていて、部員は班に所属して活動を行います。班を掛け持ちしている部員もいます。現在活動している班は「開発班」「DTM班」「セキュリティ班」「競技プログラミング班」です。

　開発班ではその名の通りゲームやスマホアプリを開発しています。主にSwift, Unity, Blenderを使っているようです。人が多くて活気があります。セキュリティ班はCTF（Capture The Flag）と呼ばれる競技の問題を通して、情報セキュリティやネットワークの基礎的な知識を得ます。部長はここにいます。競技プログラミング班では、計算機アルゴリズムやデータ構造を駆使してプログラミングで問題を解いていく方法について学習しています。毎週末AtCoderに出ていてエラい。DTM班はパソコンを用いた音楽制作を行っています。プログラミングをしない、「情報工学」色が薄い班です。

　その他プロジェクトにも参加しています。今年の11月23・24日に開催されるグルメイベント「B-1グランプリ in 明石」のWebサイトでは、各店舗での行列の待ち時間や情報を知ることができます。この待ち時間は運営が入力する仕組みになっていて、そのための内部向けシステムを情研部員有志で構築しました。参加される方は当日Webサイトで「Powered by 明石高専情報工学研究部」を探してみてください。

　さて、高専祭では毎年開発班とDTM班の作品展示がメインになります。それに対して、成果物が発生しないセキュリティ班・競技プログラミング班の部員がアウトプットする機会として部誌を用いることで、口頭・スライドよりも複雑な内容を表現しやすくなります。

　知る限りでは部誌を作るのは今年が初めてですが、積極的な部員がいくつか記事を書いてくれたのでそこそこのページ数になりました。執筆テーマを特に限定しなかった結果、アルゴリズムとリバースエンジニアリングが主な内容となりました。実際のコード等も出てきますので手を動かして理解してみるとより楽しめると思います。

　それでは、情研の薄い本をお楽しみください！

// contents

:leveloffset: +1

include::sack/index.adoc[]

include::zalgo/index.adoc[]

include::law/index.adoc[]

// include::autosel/index.adoc[]

:leveloffset: -1

[colophon]
= おわりに

　巻頭でも登場した部長です。本当はもっといろいろ書きたかった上に、他の部員からも締切近くになってから「部誌書いとけばよかった」という声が上がりました。とりあえず今年は実験ということにして、回を重ねながらブラッシュアップしたいところです。

　この部誌の印刷費用はほとんどは部長の自腹です。個人的にはそこまで痛い支出ではないのですが（自己暗示）、来年以降異なる部長の下で物理本を頒布するのは難しいかもしれません。もちろん電子版だけでも中身の公開はできるとはいえ、せっかくの年に一度の高専「祭」、フィジカルなモノが出る方が執筆に気合も入る（プレッシャーがかかる）というものです。継続的な出版のための資金をどうするか、これも今後の課題です。

　もし読んでいるあなたが国立高専機構の有力者であれば、情報工学研究部の予算を増やすよう明石高専に圧力をかけてください。あなたが明石高専関係者であれば、直前の一文を忘れてください。

// 　ちなみに、組版に使用したのはAsciidoctorです。国内であればRe:VIEWが最もメジャーであるように思われますが、なんだか複雑そうだったので選びませんでした。結局かなり苦労する羽目になりました。これについてもまたどこかにまとめようと思います。

　読みづらい箇所、誤字脱字、感想は各記事の著者もしくは奥付の連絡先にお願いします。お読みくださりありがとうございました。

<<<

{nbsp}

{nbsp}

{nbsp}

{nbsp}

{nbsp}

{nbsp}

{nbsp}

****

タイトル:: 部誌 2019
発行日:: 2019年11月9日
発行者:: 明石高専 情報工学研究部
連絡先:: sei0o@live.jp （代表）
印刷所:: 同人誌印刷所テイズプリント, pixivFACTORY

****