= 文字列アルゴリズム解説！ Z-algorithm編
naoppy <https://twitter.com/naoppyj>
v1.0, 2019-10-14
:toc:
:toc-title: 目次
:imagesdir: ./images
:encoding: utf-8
:lang: ja
:docname: Z-algorithmの解説
:figure-caption: 図
:table-caption: 表
:example-caption: 例
:author: naoppy
:revnumber: 1.0
:revdate: 2019/10/14
:icons: font
:stem: asciimath

競プロ班班長のnaoppyです。初めて部誌を書くので至らない点があるかと思いますが、どうぞ最後までよんでいただけると幸いです。

== 記法について

このドキュメントでは、以下の記法を使います。

stem:[S[i\]]::
文字列 stem:[S] の stem:[i] 番目の文字。
stem:[S[i..\]]::
文字列 stem:[S] の stem:[i] 番目を含む stem:[i] 番目以降の文字列。
stem:[S[i..j\]]::
文字列 stem:[S] の stem:[i] 番目を含む stem:[i] 番目以降で、
 stem:[j] 番目を含む stem:[j] 番目までの文字列。
stem:[S[i..j)]::
文字列 stem:[S] の stem:[i] 番目を含む stem:[i] 番目以降で、
 stem:[j] 番目を **含まない** stem:[j] 番目までの文字列。
stem:[|S|]::
文字列 stem:[S] の 長さ。

.記法
====
stem:[S] = "abcde" とする。 +
stem:[S[0\]] = "a", stem:[S[4\]] = "e"  +
stem:[S[2..\]] = "cde", stem:[S[1, 2\]] = "bc", stem:[S[1, 4)] = "bcd"
====

== 用語について

このドキュメントでは、用語を以下で定義します。

接頭辞(prefix)::
文字列 stem:[S] に対して、末尾から stem:[x] 文字削った文字列を stem:[S] の接頭辞という。 (stem:[0 <= x < |S|])
接尾辞(suffix)::
文字列 stem:[S] に対して、先頭から stem:[x] 文字削った文字列を stem:[S] の接尾辞という。 (stem:[0 <= x < |S|])
部分文字列(substring)::
文字列 stem:[S] に対して、先頭から stem:[x] 文字、末尾から stem:[y] 文字削った文字列を stem:[S] の部分文字列という。 (stem:[0 <= x + y < |S|])

.用語
====
stem:[S] = "abcde" とする。 +
stem:[S] の prefix は ["abcde", "abcd", "abc", "ab", "a"] +
stem:[S] の suffix は ["abcde", "bcde", "cde", "de", "e"] +
stem:[S] の substring は [
"abcde", "abcd", "abc", "ab", "a",
"bcde", "bcd", "bc", "b",
"cde", "cd", "c",
"de", "d",
"e"
]
====

== Z-algorithmとは

文字列 stem:[S] が与えられたとき、各 stem:[i] について +
 stem:[S] と stem:[S[i..]] の最長共通接頭辞の長さ(Length of Longest Common Prefix, LCP長などという) +
を記録した配列 stem:[z] を stem:[bbbO(|S|)] で構築するアルゴリズムです。

== Z-algorithmの工夫

== Z-algorithmの実装

== 参考文献

[bibliography]
- https://snuke.hatenablog.com/entry/2014/12/03/214243 文字列の頭良い感じの線形アルゴリズムたち３ snuke
- https://ei1333.github.io/luzhiled/snippets/string/z-algorithm.html 最長共通接頭辞(Z-Algorithm) ei1333
- http://codeforces.com/blog/entry/3107 codeforces-blog paladin8